name: Publish Docker Image

on:
  push:
    branches: [ master ]

    

jobs:

  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Check out
        uses: actions/checkout@v2

        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
          
      - name: Push to ECR
        id: tag
        run: |
          aws ecr get-login-password --region ap-southeast-2  | docker login --username AWS --password-stdin 706949302588.dkr.ecr.ap-southeast-2.amazonaws.com
          docker build --tag test-hello-world:v1.${GITHUB_RUN_NUMBER} .
          echo "::set-output name=tag::v1.${GITHUB_RUN_NUMBER}"
          docker push test-hello-world:v1.${GITHUB_RUN_NUMBER}


  update-dev-image:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'heads')
    needs:
    - build
    steps:
    - uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: 3.8.6
    - run: git clone https://${REPO_TOKEN}@github.com/subudear/gitops-infra-helloworld.git .
      env:
        REPO_TOKEN: ${{secrets.REPO_TOKEN}}
    - run: kustomize edit set image 706949302588.dkr.ecr.ap-southeast-2.amazonaws.com/test-hello-world:"${{ needs.build.outputs.output1 }}"
      working-directory: ./deploy/enviroments/dev
    - run: git add .
    - run: |
        git config user.email "$EMAIL"
        git config user.name "$GITHUB_ACTOR"
      env:
        EMAIL: ${{secrets.EMAIL}}
    - run: git commit -m "Set dev image tag to short sha"
    - run: git push
