name: Publish Docker Image

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'deploy/**'
  release:
    types:
      - published
    

jobs:

  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Check out
        uses: actions/checkout@v2


      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - id: tag
        run: |
          docker build --tag test-hello-world:v1.${GITHUB_RUN_NUMBER} .
          echo "::set-output name=tag::v1.${GITHUB_RUN_NUMBER}"
        

      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ap-southeast-2
          image: test-hello-world:v1.${GITHUB_RUN_NUMBER}

  update-dev-image:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'heads')
    needs:
    - build
    steps:
    - uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: 3.8.6
    - run: git clone https://${REPO_TOKEN}@github.com/subudear/gitops-infra-helloworld.git .
      env:
        REPO_TOKEN: ${{secrets.REPO_TOKEN}}
    - run: kustomize edit set image 706949302588.dkr.ecr.ap-southeast-2.amazonaws.com/test-hello-world:"${{ needs.build.outputs.output1 }}"
      working-directory: ./deploy/enviroments/dev
    - run: git add .
    - run: |
        git config user.email "$EMAIL"
        git config user.name "$GITHUB_ACTOR"
      env:
        EMAIL: ${{secrets.EMAIL}}
    - run: git commit -m "Set dev image tag to short sha"
    - run: git push
